[package]
name = "ex02_embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = "0.9.1"
candle-nn = "0.9.1"
hf-hub = "0.4.3"
candle-transformers = "0.9.1"

[dev-dependencies]
face-auth = { path = "../../app" }


